// Code generated by MockGen. DO NOT EDIT.
// Source: config.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// GetClientId mocks base method.
func (m *MockConfig) GetClientId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetClientId indicates an expected call of GetClientId.
func (mr *MockConfigMockRecorder) GetClientId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientId", reflect.TypeOf((*MockConfig)(nil).GetClientId))
}

// GetClientSecretKey mocks base method.
func (m *MockConfig) GetClientSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetClientSecretKey indicates an expected call of GetClientSecretKey.
func (mr *MockConfigMockRecorder) GetClientSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientSecretKey", reflect.TypeOf((*MockConfig)(nil).GetClientSecretKey))
}

// GetSpotifySearchApi mocks base method.
func (m *MockConfig) GetSpotifySearchApi() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotifySearchApi")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSpotifySearchApi indicates an expected call of GetSpotifySearchApi.
func (mr *MockConfigMockRecorder) GetSpotifySearchApi() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotifySearchApi", reflect.TypeOf((*MockConfig)(nil).GetSpotifySearchApi))
}

// GetTokenIssuerUrl mocks base method.
func (m *MockConfig) GetTokenIssuerUrl() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenIssuerUrl")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTokenIssuerUrl indicates an expected call of GetTokenIssuerUrl.
func (mr *MockConfigMockRecorder) GetTokenIssuerUrl() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenIssuerUrl", reflect.TypeOf((*MockConfig)(nil).GetTokenIssuerUrl))
}
